# Generated by Django 4.1.3 on 2022-11-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soclean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='state',
            field=models.CharField(default='Texas', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='town',
            field=models.CharField(default='Amarillo', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
